# .github/workflows/daily-bot.yml
name: Daily Bot - Acessar Site

on:
  schedule:
    # Todo dia às 9:00 AM (Brasil = UTC-3, então 12:00 UTC)
    - cron: '0 12 * * *'
  
  # Permite executar manualmente
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v4
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 📦 Instalar dependências
        run: npm install
      
      - name: 🚀 Executar bot
        run: npm run start
        env:
          TZ: America/Sao_Paulo
      
      - name: 📊 Log de conclusão
        run: echo "✅ Bot executado com sucesso em $(date)"